# -*- mode: python ; coding: utf-8 -*-
# App.spec - Flask Application Build Configuration

import os
from pathlib import Path

current_dir = os.path.dirname(os.path.abspath('app.py'))

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[current_dir],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('moduller', 'moduller'),
        ('.env', '.'),
        ('.env.template', '.'),
        ('themes.json', '.'),
        ('rules', 'rules'),
        ('data', 'data'),
        ('user_cache', 'user_cache'),
    ],
    hiddenimports=[
        'flask',
        'flask_mail',
        'werkzeug',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'openai',
        'pymysql',
        'cryptography',
        'boto3',
        'botocore',
        'dotenv',
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'smtplib',
        'threading',
        'json',
        'datetime',
        'os',
        'sys',
        'time',
        'logging',
        'webbrowser',
        'subprocess',
        'psutil',
        'multiprocessing',
        'pathlib',
        'mss',
        'mss.tools',
        'signal',
        'traceback',
        'hashlib',
        'base64',
        'uuid',
        'tempfile',
        'shutil',
        'socket',
        'ssl',
        'platform',
        'concurrent',
        'concurrent.futures',
        'cv2',
        'numpy',
        'PIL',
        'PIL.Image',
        'pyautogui',
        'io',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'scipy',
        'tensorflow',
        'torch',
        'aiohttp',
        'websockets',
        'uvloop',
        'uvicorn',
        'fastapi',
        'tkinter',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DDSFocusPro-App',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Console for Flask app monitoring
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)